### ISSUE TITLE
Fix rotating the `SECRET_KEY` — breaks authentication

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#26]
### Business Reason ### 

As a developer, I will be able to rotate the `SECRET_KEY` so that I can respond to security incidents.

### Acceptance Criteria ### 

**If** the `SECRET_KEY`  is rotated
**When** needed
**Then** user authentication should continue to work.

**Example**
In settings/base.py, I set
`SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', get_random_string(50))`
which rotated the secret key due to there being no environment variable set. Then, when trying to log in got the following error in the logs. Noting that the user received no error.
```
   2022-02-01T10:22:29.42-0500 [APP/PROC/WEB/0] ERR 2022-02-01 10:22:29,425 [WARNING] django.request: Bad Request: /api/v1/user/login/verify
   2022-02-01T10:22:34.22-0500 [APP/PROC/WEB/0] ERR [2022-02-01 15:22:34 +0000] [219] [INFO] Booting worker with pid: 219
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR --- Logging error ---
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/app/django-backend/fecfiler/password_management/views.py", line 131, in token_verification
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR     payload = verify_token(token_received)
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/app/django-backend/fecfiler/password_management/views.py", line 162, in verify_token
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR     payload = jwt.decode(token_received, key=SECRET_KEY, algorithms='HS256', options=options)
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/jwt/api_jwt.py", line 93, in decode
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR     jwt, key=key, algorithms=algorithms, options=options, **kwargs
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/jwt/api_jws.py", line 157, in decode
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR     key, algorithms)
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/jwt/api_jws.py", line 224, in _verify_signature
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR     raise InvalidSignatureError('Signature verification failed')
   2022-02-01T10:22:34.24-0500 [APP/PROC/WEB/0] ERR jwt.exceptions.InvalidSignatureError: Signature verification failed
  
   ```

Looks like this might not be specific to our implementation and more of a Django issue. Here's an article: https://eralpb.medium.com/changing-rotating-django-secret-key-without-logging-users-out-804a29d3ea65
However, initial research suggests that rotating the secret key should log users out and invalidate their session, not prevent their ability to log in ever.

### Dev Notes
- [ ] please test Login.gov and legacy user login on Dev and Local
- [ ] Audit e2e database and Django fixtures and purge sensitive information (including hard coded passwords for local test user) no longer needed after Login.gov integration

### QA Notes
test Legacy login and Login.gov on DEV

**Comment by dheitzer** [comment]
Possibly related https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-SECRET_KEY_FALLBACKS (Since Django 4.1)

**Comment by Elaine-Krauss-TCG** [comment]
Rotating the secret key no longer breaks authentication.  This has changed because at some point in the last two years, we switched from a custom user-authentication system to one built on top of Django's AbstractUser.  This does not use the secret key to hash user passwords, unlike the previous custom authentication system.  For details on how passwords are hashed under the current version of Django, see the documentation [here](https://docs.djangoproject.com/en/5.0/topics/auth/passwords/).  To rotate the secret key, the environment variable controlling it must be changed, and then the API needs to be redeployed.

Rotating the secret key does invalidate existing sessions; this forces users currently logged in to log in again.  Django offers a solution to this in the form of the SECRET_KEY_FALLBACKS setting, which allows you to (temporarily) store the previous secret key, giving users a window of time where sessions with both the previous and the new secret keys can be used.  We could set things up so that this setting can be adjusted with a new environment variable, but it would require another redeploy to clear it out after a suitable duration has passed.

@lbeaufort any thoughts, input, or concerns would be appreciated.

**Comment by Elaine-Krauss-TCG** [comment]
> [@Elaine-Krauss-TCG](https://github.com/Elaine-Krauss-TCG) this is great news, thanks for your thorough documentation. Sounds good, if you haven't already making sure that our local test user login still works is my only thought, since that password was created a while back. Thanks again!

The local test user can log in without issue, thankfully.  This potential pitfall was most likely resolved when we switched to using Django's Abstract User.

I'd be interested in your thoughts on whether or not the hassle of managing the SECRET_KEY_FALLBACKS is worth the utility of avoiding users being logged out when we rotate the secret key.  It would roughly double the work required to rotate the secret key, given that we would have to go back in and remove the fallback key after a few hours or a day and then do another redeploy.

**Comment by lbeaufort** [comment]
> I'd be interested in your thoughts on whether or not the hassle of managing the SECRET_KEY_FALLBACKS is worth the utility of avoiding users being logged out when we rotate the secret key. It would roughly double the work required to rotate the secret key, given that we would have to go back in and remove the fallback key after a few hours or a day and then do another redeploy.

@Elaine-Krauss-TCG great question - it seems like it would add value, and the drawbacks seem fairly minimal. We could consider whether it would make sense to auto-generate the `SECRET_KEY_FALLBACKS` value upon deploy. I think a spike ticket would be helpful, if you don't mind entering one. cc: @mjtravers

**Comment by mjtravers** [comment]
Follow up ticket: #852 

No code for CR. Research findings are in the comments above.

Sending to QA.

**Comment by WiseQA** [comment]
No code change and no QA review needed on this ticket.

Moved to Stage Ready.
