### ISSUE TITLE
Remove external FEC API calls in unit tests

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#64]
Automated tests should not be calling external services. The below tests are calling the FEC API. If the FEC API goes down, the tests will fail and we will be unable to deploy. We should either remove or modify these tests to use mocked results:

```
======================================================================
ERROR: test_get_election_year (fecfiler.core.tests.SimpleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/nxg_fec/fecfiler/core/aggregation_helper.py", line 832, in get_election_year
    results = results + ab.json()["results"]
KeyError: 'results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nxg_fec/fecfiler/core/tests.py", line 11, in test_get_election_year
    result = get_election_year("H", "NJ", "01")
  File "/opt/nxg_fec/fecfiler/core/aggregation_helper.py", line 852, in get_election_year
    "The get_election_year function is throwing an error: " + str(e)
Exception: The get_election_year function is throwing an error: 'results'

======================================================================
ERROR: test_get_election_year (fecfiler.sched_F.tests.SimpleTest)

```

**Comment by mjtravers** [comment]
Unit test code that made external calls was refactored out of the code when legacy code was moved into the code backlog.
Closing ticket.
